# -*- coding: utf-8 -*-
"""task03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fuUB6bmZUAZ-IhGHm4jbKvTrU7IH5Lrv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#import dataset
df = pd.read_csv("/content/drive/MyDrive/Elevate Labs/TASK03/Housing.csv")

df.head()

df.columns

df.info()

df.isnull().sum()

"""Convert categorical values"""

from sklearn.preprocessing import LabelEncoder

# Create an instance of LabelEncoder
label_encoder = LabelEncoder()

df = df.apply(label_encoder.fit_transform)

df.tail()

"""Split Data"""

from sklearn.model_selection import train_test_split

df.columns

X = df.drop(['price'], axis=1)

y = df['price']

# Step 3: Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""Linear Regression"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

model = LinearRegression()
model.fit(X_train, y_train)

#Make predictions
y_pred = model.predict(X_test)

#Evaluate model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error: {mae:.4f}")
print(f"Mean Squared Error: {mse:.4f}")
print(f"R-squared: {r2:.4f}")

"""Plotting"""

print("X", X.shape)
print("y", y.shape)

#Plot regression line
plt.scatter(y_test, y_pred, color='purple')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')  # 45-degree line
plt.xlabel("Actual Target")
plt.ylabel("Predicted Target")
plt.title("Predicted vs Actual")
plt.show()

"""Coefficient Interpretation"""

#Interpret coefficients
print(f"Intercept:{model.intercept_:.4f}")
print(f"Coefficient:{model.coef_[0]:.4f}")

"""Predict new input"""

# Create new house input
new_house = pd.DataFrame({
    'area': [3000],
    'bedrooms': [3],
    'bathrooms': [2],
    'stories': [2],
    'mainroad': [1],          # encoded
    'guestroom': [0],
    'basement': [1],
    'hotwaterheating': [0],
    'airconditioning': [1],
    'parking': [2],
    'prefarea': [1],
    'furnishingstatus': [2]
})

# Predict
predicted_price = model.predict(new_house)

print("Predicted Price:", predicted_price[0])